export enum EnumActionType {
    SET_HOME_ACTIVE = 'SET_HOME_ACTIVE',
    SET_FORM_ACTIVE = 'SET_FORM_ACTIVE',
    SET_ABOUT_ACTIVE = 'SET_ABOUT_ACTIVE',
    SET_CONTACT_ACTIVE = 'SET_CONTACT_ACTIVE',
    SET_SKILLS_ACTIVE = 'SET_SKILLS_ACTIVE',
    SET_PORTFOLIO_ACTIVE = 'SET_PORTFOLIO_ACTIVE',
    SET_LOADING_ACTIVE = 'SET_LOADING_ACTIVE',
}

